### ISSUE TITLE
Make this lib available on crates.io

### ISSUE THREAD

**Issue by fishi0x01** [jesterpm/libdb-rs#1]
Is this project still maintained? 
If so, do you mind publishing it on crates.io?

**Comment by jesterpm** [comment]
I'm not currently using this library. However, if it is useful to you I can publish it to crates.io. 

Alternatively, you're welcome to claim the name and publish it.

**Comment by fishi0x01** [comment]
Ok cool. I am using this library actively for a project I am currently working on. It is likely I will add some more changes in the (near) future. I will publish the modified fork on crates.io and highlight your repo as origin in `README`.

Thx Jesse :bowing_man:

**Comment by fishi0x01** [comment]
I have published the crates today:

https://crates.io/crates/libdb-sys
https://crates.io/crates/libdb

Please let me know if I should add you to the author list, i.e., if you want to be officially affiliated with those published crates from the forks (https://users.rust-lang.org/t/etiquette-for-not-listing-authors/17690/)
